# 08-7. 메서드에 예외 선언하기
예외를 처리하는 방법에는 지금까지 배워 온 try-catch문을 사용하는 것 외에, 예외를 메서드에 선언하는 방법이 있다.
메서드에 예외를 선언하려면, 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어주기만 하면 된다. 
그리고 예외가 여러 개일 경우에는 쉼표(,)로 구분한다.
```java
void method() throws Exception1, Exception2, ... ExceptionN {
  //메서드의 내용
}
```
만일 모든 예외의 최고조상인 Exception클래스를 메서드에 선언하면, 모든 종류의 예외가 발생할 가능성이 있다는 뜻이다.
Exception 예외뿐만 아니라 그 자손타입의 예외까지도 발생할 수 있다는 점에 주의하자. 
앞서 오버라이딩에서 살펴본 것과 같이, 오버라이딩할 때는 단순히 선언된 예외의 개수가 아니라 상속관계까지 고려해야 한다.
> 오버라이딩의 조건 中... (p.328)   
> 조상 클래스의 메서드보다 많은 수의 예외를 선언할 수 없다.
> 단순히 선언된 예외 개수의 문제가 아니라 Exception은 모든 예외의 최고 조상이므로 가장 많은 개수의 예외를 던질 수 있도록 선언한 것과 같다.

메서드의 선언부에 예외를 선언함으로써 메서드를 사용하려는 사람이 메서드의 선언부를 보았을 때,
이 메서드를 사용하기 위해서는 어떠한 예외들이 처리되어져야 하는지 쉽게 알 수 있다.

메서드에 예외를 선언할 때 일반적으로 RuntimeException클래스들은 적지 않는다. 
이 들을 메서드 선언부의 throws에 선언한다고 해서 문제가 되지는 않지만, 보통 반드시 처리해주어야 하는 예외들만 선언한다.

사실 예외를 메서드의 throws에 명시하는 것은 예외를 처리하는 것이 아니라, 
자신(예외가 발생할 가능성이 있는 메서드)을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것이다.
예외를 전달받은 메서드가 또다시 자신을 호출한 메서드에게 전달할 수 있으며, 
이런 식으로 계속 호출스택에 있는 메서드들을 따라 전달되다가 제일 마지막에 있는 main메서드에서도 예외가 처리되지 않으면, 
main메서드마저 종료되어 프로그램이 전체가 종료된다.
```java
```
```
```
method2()에서 예외가 강제적으로 발생했으나 try-catch문으로 예외처리를 해주지 않았으므로, 
method2()는 종료되면서 예외를 자신을 호출한 method1()에게 넘겨준다. 
method1()에서도 역시 예외처리를 해주지 않았으므로 종료되면서 main메서드에게 예외를 넘겨준다.
그러나 main메서드에서 조차 예외처리를 해주지 않았으므로 main메서드가 종료되어 프로그램이 예외로 인해 비정상적으로 종료되는 것이다.

이처럼 예외가 발생한 메서드에서 예외처리를 하지 않고 자신을 호출한 메서드에게 예외를 넘겨줄 수는 있지만,
이것으로 예외가 처리된 것은 아니고 예외를 단순히 전달만 하는 것이다. 
결국 어느 한 곳에서는 반드시 try-catch문으로 예외처리를 해주어야 한다.
```java
```
```
```
```java
```
```
```
첫 번째 예제는 method1()에서 예외처리를 했고, 두 번째 예제는 method1()에서 예외를 선언하여 자신을 호출하는 메서드(main메서드)에 예외를 전달했으며, 
호출한 메서드(main메서드)에서는 try-catch문으로 예외처리를 했다.

예외가 발생한 메서드(method1) 내에서 처리되어지면, 호출한 메서드(main메서드)에서는 예외가 발생했다는 사실조차 모르게 된다.
그러나, 예외를 처리하지 않고 호출한 메서드로 넘겨주면, 호출한 메서드에서는 method1()을 호출한 라인에서 예외가 발생한 것으로 간주되어 이에 대한 처리를 하게 된다.
```java
```
```
```
이 예제는 예외가 발생한 메서드에서 직접 예외를 처리하도록 되어 있다. 그렇기 때문에, main메서드에서는 예외가 발생한 사실을 알지 못한다.
> File클래스의 createNewFile()은 예외가 선언된 메서드 이므로 finally블럭 내에 또다시 try-catch문으로 처리해야하므로 좀 복잡해진다.
> 이해를 돕기 위해 예제의 기본 흐름을 되도록 간단히 하려고 내부적으로 예외처리를 한 createNewFile(File f)메서드를 만들어서 사용했다.
```java
```
```
```
이 예제에서는 예외가 발생한 createFile메서드에서 잘못 입력된 파일이름을 임의로 처리하지 않고, 
호출한 main메서드에게 예외가 발생했음을 알려서 파일이름을 다시 입력 받도록 하였다.

이처럼 예외가 발생한 메서드 내에서 자체적으로 처리해도 되는 것은 메서드 내에서 try-catch문을 사용해서 처리하고,
메서드에 호출 시 넘겨받아야 할 값(fileName)을 다시 받아야 하는 경우(메서드 내에서 자체적으로 해결이 안 되는 경우)에는 예외를 메서드에 선언해서, 호출한 메서드에서 처리해야한다.
